## Basic Configuration

baseurl = "https://sharadroy.github.io"
builddrafts = false
canonifyurls = false
languageCode = "en"

author = "Sharad Roy"
title = "Sharad Roy"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Sharad Roy"
intro = "IIT Kanpur"
description = "Research Enginner <br/> Samsung Research Institute Bangalore"
authorimage = "prof1.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "sharadroy"
instagram = "sharadnet7"
#xing = "<username>"
linkedin = "sharadroy"
twitter = "rsharad7"
facebook = "sharadnet7"
#google = "sharadnet7"
googlescholar = "ZpgM7GYAAAAJ"
researchgate = "Sharad_Roy"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
steam = "76561198078070268"
reddit = "Rangomon"
#snapchat = "<username>"
youtube = "UCffUKmoP_3bBEZSB6XsBe_A"
#keybase = "<username>"
twitch = "rangomon"
#soundcloud = "<username>"
#tumblr = "<username>"
#strava = "<username>"
#skype = "<username>"
#telegram = "<username>"
#whatsapp = "<username>"
#email = "you@example.com"

## Extras
[params.extra]
copyright = "© 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "publications"
    weight = 2
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "contact"
    identifier = "coderag"
    weight = 3
    url = "/coderag/"
